### ISSUE TITLE
and_raise doesn't return self on any_instance matchers

### ISSUE THREAD

**Issue by rwz** [rspec/rspec-mocks#1010]
```ruby
describe "#raise_error failure" do
  it "works" do
    expect(Object).to receive(:foo).and_raise(RuntimeError).at_least(:once)
    expect{ Object.foo }.to raise_error(RuntimeError)
  end

  it "works too" do
    expect_any_instance_of(Object).to receive(:foo).at_least(:once).and_raise(RuntimeError)
    expect{ Object.new.foo }.to raise_error(RuntimeError)
  end

  it "doesn't work" do
    expect_any_instance_of(Object).to receive(:foo).and_raise(RuntimeError).at_least(:once)
    expect{ Object.new.foo }.to raise_error(RuntimeError)
  end
end
```

The result:

```
  1) #raise_error failure doesn't work
     Failure/Error: expect{ Object.new.foo }.to raise_error(RuntimeError)
       expected RuntimeError, got #<NoMethodError: undefined method `at_least' for nil:NilClass> with backtrace:
         # test.rb:16:in `block (3 levels) in <main>'
         # test.rb:16:in `block (2 levels) in <main>'
```

**Comment by JonRowe** [comment]
`and_return` and the like (including `and_raise`) is expected to be the last in the chain, we actually have specs for making sure thats the case, so this is expected behaviour.
