### ISSUE TITLE
Encounter not implement error with method stub

### ISSUE THREAD

**Issue by masolin** [rspec/rspec-mocks#1021]
Hi,
I tried to use method stubs with a real object rather than test double.
However, it will raise a not implemented exception when I use a real object.
Is this a design to force user to explicitly define a interface first? or just a bug? :confused:
Thanks a lot.
:smile:

``` ruby
require 'spec_helper'

class Foo
  # pass if msg interface defined
  # def msg; end
end

describe 'Test stub method' do
  it 'returns declared value when message is received' do
    instance = Foo.new # not implement error
    #instance = double('foo') # pass without error
    allow(instance).to receive(:msg).and_return(:return_value)
    expect(instance.msg).to equal(:return_value)
  end
end
```

``` ruby
Failures:

  1) Test stub method returns declared value when message is received
    Failure/Error: allow(instance).to receive(:msg).and_return(:return_value)
       #<Foo:0x007fa162054f78> does not implement: msg
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:86:in `block in <module:Support>'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `call'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:93:in `notify_failure'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:320:in `notify'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:304:in `__raise'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/error_generator.rb:112:in `raise_unimplemented_error'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:41:in `ensure_implemented'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/verifying_proxy.rb:24:in `add_stub'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:96:in `setup_method_substitute'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:84:in `setup_mock_proxy_method_substitute'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/matchers/receive.rb:41:in `setup_allowance'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/targets.rb:45:in `define_matcher'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-mocks-3.3.2/lib/rspec/mocks/targets.rb:14:in `block in delegate_to'
     # ./spec/controllers/concerns/test_stub_spec.rb:9:in `block (2 levels) in <top (required)>'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `instance_exec'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:206:in `block in run'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `block in run'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:478:in `run'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:203:in `run'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:559:in `block in run_examples'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `map'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:521:in `run'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `map'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
     # /Users/maso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<top (required)>'
     # /Users/maso/.rbenv/versions/2.2.3/bin/rspec:23:in `load'
     # /Users/maso/.rbenv/versions/2.2.3/bin/rspec:23:in `<main>'

```

**Comment by JonRowe** [comment]
You've encountered the verify partial doubles feature, this feature fails your test if you stub a method that doesn't exist on a real object. :)

**Comment by masolin** [comment]
Thanks a lot. I will check the feature you mentioned. :smile:
