### ISSUE TITLE
Undefined method `allow`

### ISSUE THREAD

**Issue by itsmechlark** [rspec/rspec-mocks#1029]
I encounter problem with `undefined method `allow'` and I couldn't find any solution in web so I end up here. Thanks.

```
require 'rails_helper'
require 'base_search'

RSpec.describe 'Api::V1::Search::Sorting' do
  class SortingClass
    include Api::V1::Search::Sorting

    def method_missing(method_name, *args, &block)
      send(method_name, *args, &block)
    end
  end

  let!(:instance) { SortingClass.new  }

  before(:each) { allow(instance).to receive(:field?).and_return(true) }

  describe '#sorting_options_for' do
    it { expect(instance.sorting_options_for({})).to eq({}) }
  end
end
```

```
Failure/Error: before(:each) { allow(instance).to receive(:field?).and_return(true) }
     NoMethodError:
       undefined method `allow' for #<RSpec::ExampleGroups::ApiV1SearchSorting::SortingOptionsFor:0x000000056a0ba8>
     # ./spec/search/sorting_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/config/database_cleaner.rb:11:in `block (3 levels) in <top (required)>'
     # /home/itsmechlark/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /home/itsmechlark/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/base.rb:92:in `cleaning'
     # /home/itsmechlark/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /home/itsmechlark/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `call'
     # /home/itsmechlark/.rvm/gems/ruby-2.2.3/gems/database_cleaner-1.5.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/config/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'
```

rspec v3.3.0
rspec-core v3.3.2
rspec-expectations v3.3.1
rspec-mocks v3.3.2
rspec-rails v3.3.3
rspec-support v3.3.0

**Comment by JonRowe** [comment]
Do you have the expect syntax enabled? (Check your `rails_helper` / `spec_helper`)

**Comment by itsmechlark** [comment]
I found the problem, I didn't remove the `mocha`. Thanks.
