### ISSUE TITLE
Enhance error stacktrace for receive matcher

### ISSUE THREAD

**Issue by MartinKoerner** [rspec/rspec-mocks#1059]
Hi,

most of the time, when we use the `receive` matcher on an existing object, we want do ensure, that the object also responds to this method.
```ruby
obj = SomeObject.new
expect(obj).to respond_to(:some_method)
expect(obj).to receive(:some_method)
```

I think it's OK, that rspec doesn't check this as default, because of dynamic methods.
In order to save us some code, we wrote a method `def expect_respond_and_receive`, which combines both calls. Now we have one problem:

If the `respond_to` matcher fails, the stack trace is shown correctly:

    Failure/Error: expect(caller).to respond_to(method)
       expected #<SomeObject:0x007fa83bda6570> to respond to :some_method
     # ./spec/support/spec_helper_methods.rb:106:in `expect_respond_and_receive'
     # ./spec/services/my_spec.rb:12:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

But if the `receive` matcher fails, the line of the failing spec is missing, leaving us no real clue, where the error happend:

    Failure/Error: expect(caller).to receive(method)
     
       (#<SomeObject:0x007fa8395a2448>).some_method(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/support/spec_helper_methods.rb:108:in `expect_respond_and_receive'
     # -e:1:in `<main>'

Is there a way to avoid this?

**Comment by JonRowe** [comment]
Sure use compound matchers: `expect(obj).to respond_to(:some_method).and receive(:some_method)`

**Comment by MartinKoerner** [comment]
Thanks, but I also can't use this in any helper method, because the real line of error is not present in the backtrace

**Comment by myronmarston** [comment]
This is what verifying doubles are for. Check out the verifying_partial_doubles option.

**Comment by MartinKoerner** [comment]
This is indeed a great option, thanks for the hint.
But because it is a global option, it has some downsides. E.g. `ActionView::TestCase::TestController` does not inherit from `ApplicationController`. So when I want to stub some controller method in my view specs I can't verify my views respond to the controller method.

Also the general problem of being unable to move some `expect(...).to receive(...)` calls to a helper method (for structuring my specs) still remains, as it is independent from the `respond_to` use case.

**Comment by myronmarston** [comment]
Can you put together an example app demonstrating the problem?

**Comment by MartinKoerner** [comment]
Ok I hacked a simple program with a service, were the same mock is used for create/update. For this small project it seems a litter overcomplicated but I hope you get the idea.

[rspectest.zip](https://github.com/rspec/rspec-mocks/files/114424/rspectest.zip)

**Comment by JonRowe** [comment]
@myronmarston it's well known that view specs don't work with partial doubles, as they don't have a controller you can't use controller helpers/methods.

**Comment by myronmarston** [comment]
Thanks for the example, @MartinKoerner.  Here's what's going on:

* For message expectations (`expect(...).to receive(...)`), the exception is _not_ raised when `expect(...).to receive` is called -- instead it is raised during the "verify" phase, after the example completes.
* If RSpec just raised the error at that point, and didn't do anything to the backtrace, there wouldn't be _any_ stackframes from user code in the backtrace.
* RSpec keeps track of the direct call site (e.g. one stack frame) when the message expectation was setup, and adds it to the top of the stacktrace when it raises the expectation failed error.
* Therefore, you're seeing the stackframe from the helper method, rather than the method that called the helper method.

One possible solutions is to fefactor the helper method so that it returns a compound matcher instead of setting up the expectation.  Something like:

``` ruby
module SafelyReceive
  def safely_receive(message)
    respond_to(message).and receive(message)
  end
end

RSpec.configuration do |c|
  c.include SafelyReceive
end
```

With this in place, from a spec you can do:

``` ruby
expect(obj).to safely_receive(:some_method).and_return(10)
```

It should work fine because the call site of the message expectation is still your spec rather than the helper method.  You could also look into using a spy and assert the received message after-the-fact using `expect(obj).to have_received(:method)`.

**Comment by MartinKoerner** [comment]
1. Thanks for this tip; For our respond_and_receive feature this is a very useful solution

2. Regarding the general stacktrace problem. Would it be a useful solution to remember all trace lines "above" rspec-internal lines instead only the first line?

**Comment by myronmarston** [comment]
> Regarding the general stacktrace problem. Would it be a useful solution to remember all trace lines "above" rspec-internal lines instead only the first line?

I think it would be useful.  However:

* Ruby's `caller` is surprisingly slow; see #401 where a reduction in number of times we call it yielded a large performance improvement.
* The way we get the single stack frame is using a [highly optimized method from rspec-support](https://github.com/rspec/rspec-support/blob/master/lib/rspec/support/caller_filter.rb) that performs much better than `caller`.
* As far as I can remember, you're the first user to report a problem with this.

Any solution we'd consider would need to be carefully benchmarked to make sure it performs adequately.  I doubt any of the rspec core team will take a stab at this since it isn't a widely reported problem.
