### ISSUE TITLE
Bug at proxy.rb:182: nil stub being invoked

### ISSUE THREAD

**Issue by aks** [rspec/rspec-mocks#1083]
The logic at line `proxy.rb:174` yields false if `stub` is nil.  The very next condition, at line 180, tests only `expectation`, and then invokes the nil `stub` at line 182.  This leads to an internal exception: `ArgumentError: wrong number of arguments (0 for 2)`.

![2__aks_somewhere_borg__ruby_](https://cloud.githubusercontent.com/assets/3990/14995253/b5d505e4-1128-11e6-9a44-1398ac9c9d5c.png)

**Comment by myronmarston** [comment]
@aks: can you provide an example use of rspec-mocks that triggers this sequence?

**Comment by aks** [comment]
I'm under a deadline, or I would have tried to create a simple example.  Below are snippets of the code.

This is the only test that fails.

The failure is induced in a controller spec that is attempting to confirm proper handling of AR `StaleObjectErrors`

The controller method instance variable, `@ffi_flow_function` holds a decorated (see the Draper gem) FFI::FlowFunction instance.  Hence the `.object` method.

The rspec test doubles the flow function object, and expects the various messages needed in the sequence to test the conflict detection, which causes an `StaleObjectError`.

```
 context "with conflicting saves" do
      let(:new_attrs1) { { name: "My New Name1", description: "My New Desc 1" } }
      let(:new_attrs2) { { name: "My New Name2", description: "My New Desc 2" } }

      it "intercepts conflicting saves" do
        ff1 = flow_function
        ff2 = flow_function
        ff1.update_attributes new_attrs1
        ff1.save
        ffdbl = double(ff2)
        expect(FFI::FlowFunction).to receive(:find).with(any_args).and_return(ffdbl)
        expect(ffdbl).to receive(:decorate).and_return(ffdbl)
        expect(ffdbl).to receive(:object).and_return(ffdbl)
        expect(ffdbl).to receive(:updated_by_id=).with(any_args)
        expect(ffdbl).to receive(:status).and_return(1)
        expect(ffdbl).to receive(:update_params).with(any_args).and_raise(ActiveRecord::StaleObjectError)
        put :update, {:id => ff2.to_param, :ffi_flow_function => new_attrs2 }, valid_session
        expect(flash[:error]).to be_present
      end
    end
```

The controller code being tested is here:
```
  # PATCH/PUT /ffi/flow_functions/1
  # PATCH/PUT /ffi/flow_functions/1.json
  def update
    ff_params = ffi_flow_function_params

    respond_to do |format|
      begin
        ffobj = @ffi_flow_function.object
        update_result = ffobj.update_params(ff_params)
        if update_result
          format.html { redirect_to @ffi_flow_function.object.as_parent, notice: 'Flow function was successfully updated.' }
          format.json { render :show, status: :ok, location: @ffi_flow_function}
        else
          format.html { render :edit }
          format.json { render json: @ffi_flow_function.object.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::StaleObjectError => e
        log_debug "StaleObject caught on PATCH/PUT FFI::FlowFunction"

        @ffi_conflict = FFI::Conflict.create! parameters: ff_params,
                                              class_name: @ffi_flow_function.class.to_s,
                                              record_id: @ffi_flow_function.object.id,
                                              user_id: current_user_id
        flash[:error] = "Conflict detected on update! <a href=\"#{ffi_conflict_url(@ffi_conflict)}\">Conflict(#{@ffi_conflict.id})</a>"
        format.html { render 'ffi/conflicts/show' }
        format.json { head :no_content }
      end
    end
  end
```

Here is a stacktrace:

```
=> ["/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/activerecord-4.2.5/lib/active_record/errors.rb:128:in `initialize'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:149:in `exception'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:149:in `raise'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:149:in `block in and_raise'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:660:in `call'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:660:in `block in call'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:659:in `map'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:659:in `call'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:554:in `invoke_incrementing_actual_calls_by'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/message_expectation.rb:411:in `invoke'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/proxy.rb:182:in `message_received'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/method_double.rb:77:in `proxy_method_invoked'",
 "/Users/aks/.rbenv/versions/2.2.3/gemsets/borg/gems/rspec-mocks-3.4.1/lib/rspec/mocks/method_double.rb:64:in `block (2 levels) in define_proxy_method'",
 "/Users/aks/src/ecorithm/BORG/app/controllers/ffi/flow_functions_controller.rb:100:in `block in update'",
```

**Comment by aks** [comment]
Finally, the `:update_params` method is defined within the AR subclass itself, but is added on through an included module.  The module does this:

```
module FFI::FlowFunctionUtilities
  FFI::FlowFunction.class_eval do
    ...
    def update_params in_params
      ...
    end
  end
end
```

Perhaps it's possible that the method validator in rspec is being confused by the dynamically injected method?

**Comment by aks** [comment]
This is not a bug.

The problem is that `ActiveRecord::StaleObjectError` requires two arguments, and was being raised without any arguments.

Closing this issue.

**Comment by myronmarston** [comment]
Glad you figured it out!
