### ISSUE TITLE
Verify partial doubles fails on method with default hash argument and default keyword argument

### ISSUE THREAD

**Issue by edzhelyov** [rspec/rspec-mocks#1266]
I've enabled `verify_partial_doubles` in our project and started fixing the reported issues.

There is one particular case that I'm not sure how to handle. A method with signiture `def foo(fist, foo = {}, a: false)` treats the hash passed to foo as keyword arguments. Not sure if we can patch `rspec-mocks` around this case as I haven't dig into the internals.

Any advise how to proceed?

Below is a test case that reproduce the issue againts 3.8.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rspec'
end

require 'rspec'

RSpec.configure do |config|
  config.expect_with :rspec do |c|
    c.syntax = [:should]
  end

  config.mock_with :rspec do |c|
    c.syntax = [:should]
    c.verify_partial_doubles = true
  end
end

class Receiver
  def self.track(user, event, properties = {}, identify: false); end

  def self.nokeyword(user, event, properties = {}); end

  def self.nodefault(user, event, properties, identify: false); end
end

describe 'should work' do
  it 'default hash and keyword' do
    Receiver.should_receive(:track)

    Receiver.track 1, :item_submitted, {a: 1}
  end

  it 'no keyword' do
    Receiver.should_receive(:nokeyword)

    Receiver.nokeyword 1, :item_submitted, {a: 1}
  end

  it 'no default hash' do
    Receiver.should_receive(:nodefault)

    Receiver.nodefault 1, :item_submitted, {a: 1}
  end

  it 'full arguments' do
    Receiver.should_receive(:nodefault)

    Receiver.nodefault 1, :item_submitted, {a: 1}, identify: false
  end
end

```
```
F...

Failures:

  1) should work default hash and keyword
     Failure/Error: Receiver.track 1, :item_submitted, properties

     ArgumentError:
       Invalid keyword arguments provided: a
     # ./keyword_spec.rb:72:in `submit'
     # ./keyword_spec.rb:29:in `block (2 levels) in <top (required)>'

Finished in 0.00315 seconds (files took 0.22648 seconds to load)
3 examples, 1 failure

RSpec 3.8
  - rspec-core 3.8.0
  - rspec-expectations 3.8.2
  - rspec-mocks 3.8.0
  - rspec-support 3.8.0
```

**Comment by benoittgt** [comment]
Closing because https://github.com/rspec/rspec-support/pull/366 has been merged

**Comment by JonRowe** [comment]
Do we not want to add a spec for this to ensure we don't regress mocks unintendedly?

**Comment by benoittgt** [comment]
I think it can be a good idea. I can add it.
