### ISSUE TITLE
Message expectation doesn't leverage passed matcher capabilities when reporting error.

### ISSUE THREAD

**Issue by rfronczyk** [rspec/rspec-mocks#1294]
### Subject of the issue
Calling `expect(...).to receive(...).with(...)` with a composed matcher doesn't use the full capabilities of the passed matcher in order to provide a more precise error message to the user. 

You can argue that the diff produced in the attached example is correct ( the passed array doesn't match the expected one so the messages list the whole array), that said the other example shows that it could be done better. 

### Your environment
```
* Ruby version: ruby-2.4.6
* rspec-mocks version: 3.7.0

### Steps to reproduce
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.7.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

class A
  def test(params)
  end
end

B = Struct.new(:a, :b)

RSpec.describe 'additions' do
  let(:test_double) {  instance_double(A) }

  let(:passed_attributes) do
    [
      B.new(1, 2),
      B.new(3, 4),
      B.new(5, 6),
      B.new(7, 8)
    ]
  end

  let(:attribute_matcher) do
    [
      have_attributes(a: 1, b: 2),
      have_attributes(a: 3, b: 4),
      have_attributes(a: 5, b: 10),
      have_attributes(a: 7, b: 8)
    ]
  end

  it 'shows the whole array instead of elements which dont match' do
    expect(test_double).to receive(:test).with(a_collection_containing_exactly(*attribute_matcher))
    test_double.test(passed_attributes)
  end

  it 'shows only not matching elements' do
    expect(passed_attributes).to contain_exactly(*attribute_matcher)
  end
end
```
### Expected behavior
I would expect that error message shows only elements of the array which don't match the expectation.

### Actual behavior
Error message lists the whole array.

**Comment by rfronczyk** [comment]
Rspec output:
```
Randomized with seed 7867
FF

Failures:

  1) additions shows the whole array instead of elements which dont match
     Failure/Error: test_double.test(passed_attributes)

       #<InstanceDouble(A) (anonymous)> received :test with unexpected arguments
         expected: (a collection containing exactly (have attributes {:a => 1, :b => 2}), (have attributes {:a => 3, :b => 4}), (have attributes {:a => 5, :b => 10}), and (have attributes {:a => 7, :b => 8}))
              got: ([#<struct B a=1, b=2>, #<struct B a=3, b=4>, #<struct B a=5, b=6>, #<struct B a=7, b=8>])
       Diff:
       @@ -1,2 +1,5 @@
       -["a collection containing exactly (have attributes {:a => 1, :b => 2}), (have attributes {:a => 3, :b => 4}), (have attributes {:a => 5, :b => 10}), and (have attributes {:a => 7, :b => 8})"]
       +[[#<struct B a=1, b=2>,
       +  #<struct B a=3, b=4>,
       +  #<struct B a=5, b=6>,
       +  #<struct B a=7, b=8>]]

     # rspec_report.rb:47:in `block (2 levels) in <main>'

  2) additions show only not matching elements
     Failure/Error: expect(passed_attributes).to contain_exactly(*attribute_matcher)

       expected collection contained:  [(have attributes {:a => 1, :b => 2}), (have attributes {:a => 3, :b => 4}), (have attributes {:a => 5, :b => 10}), (have attributes {:a => 7, :b => 8})]
       actual collection contained:    [#<struct B a=1, b=2>, #<struct B a=3, b=4>, #<struct B a=5, b=6>, #<struct B a=7, b=8>]
       the missing elements were:      [(have attributes {:a => 5, :b => 10})]
       the extra elements were:        [#<struct B a=5, b=6>]
     # rspec_report.rb:51:in `block (2 levels) in <main>'

Finished in 0.03244 seconds (files took 0.07576 seconds to load)
2 examples, 2 failures

Failed examples:

rspec rspec_report.rb:45 # additions shows the whole array instead of elements which dont match
rspec rspec_report.rb:50 # additions show only not matching elements
```

**Comment by JonRowe** [comment]
This behaviour is complex as mocks matchers are not real matchers in the way they are verified, there is certainly scope for doing this if someone is interested but probably not that high on my list right now. (Also apologies for taking this long to come back to you!)

**Comment by rfronczyk** [comment]
No worries :)

I took a brief look at the code and it looked like this might be a bigger change. But if you think there is a simple way of doing this I would be happy to help.
