### ISSUE TITLE
Negative expectation failures should be surfaced during verification

### ISSUE THREAD

**Issue by x-yuri** [rspec/rspec-mocks#874]
Consider the following app:

`Gemfile`:

```ruby
source "https://rubygems.org"
ruby '2.1.5'

gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git', ref: 'b39d72d'
gem 'sentry-raven', '~>0.12.2'
gem 'rspec', '~>3.1.0'
gem 'rack-test', '~>0.6.2'
```

`1.rb`:

```ruby
require 'rubygems'
require 'bundler/setup'

require 'sinatra'
require 'sentry-raven'

Raven.configure(true) do |config|
  config.dsn = '...'
end

use Raven::Rack

get '/' do
  raise 'test exception'
end

ENV['RACK_ENV'] = 'test'

require 'rack/test'

describe 'app' do
  include Rack::Test::Methods

  def app
    @app || Sinatra::Application
  end

  it 'passes errors to Raven' do
    expect(Raven.client).not_to receive(:send)
    # expect(Raven.client).to receive(:send)   # works the same as previous line
    get '/'
  end
end
```

Additionally, I've added some debug statements:

https://github.com/getsentry/raven-ruby/blob/0.12.3/lib/raven/base.rb#L75:

```ruby
    def send(evt)
puts 'inside Raven.send'
p client.method(:send).source_location
      client.send(evt)
```

https://github.com/getsentry/raven-ruby/blob/0.12.3/lib/raven/client.rb#L25:

```ruby
    def initialize(configuration)
puts 'inside Raven::Client.initialize'
      @configuration = configuration
```

https://github.com/getsentry/raven-ruby/blob/0.12.3/lib/raven/client.rb#L19:

```ruby
    def send(event)
puts 'inside Raven::Client#send'
      unless configuration.send_in_current_environment?
```

Then, when I run the spec:

```
$ rspec 1.rb
inside Raven::Client.initialize
D, [2015-01-21T13:15:45.492433 #19390] DEBUG -- : ** [Raven] Collecting RuntimeError: test exception
inside Raven.send
["/home/yuri/.gem/ruby/2.1.5/gems/rspec-mocks-3.1.3/lib/rspec/mocks/method_double.rb", 59]
.

Finished in 0.07989 seconds (files took 0.40847 seconds to load)
1 example, 0 failures
```

But the test should fail. Now if I comment the expectation out:

```
inside Raven::Client.initialize
D, [2015-01-21T13:16:47.920593 #19406] DEBUG -- : ** [Raven] Collecting RuntimeError: test exception
inside Raven.send
["/home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb", 26]
inside Raven::Client#send
D, [2015-01-21T13:16:47.933273 #19406] DEBUG -- : ** [Raven] Sending event 39925f25c66832e9c9dcaa47059d0a6f to Sentry
E, [2015-01-21T13:16:48.016546 #19406] ERROR -- : ** [Raven] Unable to record event with remote Sentry server (Raven::Error - Unknown transport scheme '')
E, [2015-01-21T13:16:48.016722 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb:91:in `transport'
E, [2015-01-21T13:16:48.016761 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/client.rb:45:in `send'
E, [2015-01-21T13:16:48.016798 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:78:in `send'
E, [2015-01-21T13:16:48.016835 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:116:in `block in capture_exception'
E, [2015-01-21T13:16:48.016871 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:143:in `send_or_skip'
E, [2015-01-21T13:16:48.016907 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/base.rb:110:in `capture_exception'
E, [2015-01-21T13:16:48.016943 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:29:in `capture_exception'
E, [2015-01-21T13:16:48.016978 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:66:in `rescue in call'
E, [2015-01-21T13:16:48.017013 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/sentry-raven-0.12.3/lib/raven/integrations/rack.rb:60:in `call'
E, [2015-01-21T13:16:48.017060 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
E, [2015-01-21T13:16:48.017096 #19406] ERROR -- : ** [Raven] /home/yuri/.gem/ruby/2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
E, [2015-01-21T13:16:48.017136 #19406] ERROR -- : ** [Raven] Failed to submit event: RuntimeError: test exception
.

Finished in 0.15771 seconds (files took 0.40316 seconds to load)
1 example, 0 failures
```

**Comment by x-yuri** [comment]
And now consider using `mocha`:

`Gemfile`:

```ruby
...
gem 'rack-test', '~>0.6.2'
gem 'mocha', '~>1.1.0'
```

`1.rb`:

```ruby
require 'rubygems'
...
require 'rack/test'

RSpec.configure do |config|
  config.mock_with :mocha
end

describe 'app' do
  ...
  it 'passes errors to Raven' do
    Raven.client.expects(:send)   # Raven.client.expects(:send).never
    get '/'
  end
end
```

Then:

```
$ rspec 1.rb
inside Raven::Client.initialize
D, [2015-01-21T14:04:10.503716 #23500] DEBUG -- : ** [Raven] Collecting RuntimeError: test exception
inside Raven.send
["/home/yuri/.gem/ruby/2.1.5/gems/mocha-1.1.0/lib/mocha/class_method.rb", 62]
.

Finished in 0.08241 seconds (files took 0.45779 seconds to load)
1 example, 0 failures
```

And with `.expects(:send).never`:

```
inside Raven::Client.initialize
D, [2015-01-21T14:05:04.584304 #23556] DEBUG -- : ** [Raven] Collecting RuntimeError: test exception
inside Raven.send
["/home/yuri/.gem/ruby/2.1.5/gems/mocha-1.1.0/lib/mocha/class_method.rb", 62]
F

Failures:

  1) app passes errors to Raven
     Failure/Error: Raven.client.expects(:send).never
     Mocha::ExpectationError:
       not all expectations were satisfied
       unsatisfied expectations:
       - expected never, invoked once: #<Raven::Client:0x7f2315649490>.send(any_parameters)
     # ./1.rb:33:in `block (2 levels) in <top (required)>'

Finished in 0.05607 seconds (files took 0.42729 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./1.rb:32 # app passes errors to Raven
```

**Comment by x-yuri** [comment]
Well, it must be because `sinatra` was running in `development` environment and catched all exceptions to show them in a [pretty](https://github.com/sinatra/sinatra/blob/v1.4.5/lib/sinatra/show_exceptions.rb#L22-39) [way](http://www.sinatrarb.com/intro.html) (`show_exceptions` settings). In other words, `ENV['RACK_ENV'] = 'test'` must be before `require 'sinatra'`.

**Comment by JonRowe** [comment]
Yep

**Comment by myronmarston** [comment]
I've dug into this a bit to understand why mocha works correctly here while RSpec doesn't and I see what's going on.  When you expect that a message is not received with rspec-mocks, it prepares the object so that if it does receive the message, it will raise an exception immediately at that point of time and halt the example with that failure.  If the exception is rescued (which is what sinatra does when `ENV['RACK_ENV']` is not "test"), then the example will pass because the failure that RSpec was triggering was caught and silenced.

In mocha, it also raises the error immediately, but it _also_ has logic in the end-of-example mock verification that fails the example again if a message was received that was specifically expected to not be received.  Thus mocha is immune to intermediaries rescuing the eager error while RSpec is not.

I think this is something we can and should fix -- as you found, users aren't always aware that their web framework is rescuing and silencing errors for them, and in those situations RSpec's behavior can appear baffling.

**Comment by samphippen** [comment]
We can close this because of #884
