### ISSUE TITLE
'anything' argument matcher does not work with Java objects (in JRuby) in RSpec 3

### ISSUE THREAD

**Issue by asthasr** [rspec/rspec-mocks#877]
While working with a spec in our JRuby project, we noticed a regression: we receive a long stack trace when a method that has been stubbed with an `anything` matcher receives a Java object. This appears to be due to the `#equals` method being called on the Java object, passing a `RubyObject` proxy. This is likely due to an ordering issue with the `===` operator; the Ruby object should instead be responsible for determining equality. (Of course, in this case, `anything` should simply return `True`.)

```java
java.lang.ClassCastException: org.jruby.RubyObject cannot be cast to com.ourcompany.Entity
  at com.ourcompany.Entity.equals(Entity.java:3098)
  at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:455)
  at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:316)
  at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:61)
  at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
  at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
    at org.jruby.runtime.callsite.EqCallSite.call(EqCallSite.java:37)
    at rubyjit.Module$$values_match?_B1935D8255AC9E55FF8B740CDC034321F0EFC1F2386229603.__file__(/.../rails/vendor/bundle/jruby/1.9/gems/rspec-support-3.1.2/lib/rspec/support/fuzzy_matcher.rb:12)
    at rubyjit.Module$$values_match?_B1935D8255AC9E55FF8B740CDC034321F0EFC1F2386229603.__file__(/.../rails/vendor/bundle/jruby/1.9/gems/rspec-support-3.1.2/lib/rspec/support/fuzzy_matcher.rb)
```

This is the original stub which led to the issue:

```ruby
allow(entity_settings).to receive(:our_method).with('A STRING', anything).and_return 0
```

**Comment by benissimo** [comment]
This issue only came up once we upgraded to rspec 3. We did not have trouble passing java objects to `anything` matchers with rspec 2.

We're using jruby version 1.7.6 FYI.

**Comment by myronmarston** [comment]
Thanks for reporting this.  FIrst step for me is to come up with a failing spec, and I'm having trouble doing that.  I tried in IRB to create a java object to see it fail with the kind of error you printed above, but I haven't found a way to do that:

```
➜ chruby jruby
➜ irb
irb(main):001:0> require 'java'
=> false
irb(main):002:0> java.lang.String
=> Java::JavaLang::String
irb(main):003:0> java.lang.String.new("abc")
=> #<Java::JavaLang::String:0x23bca486>
irb(main):004:0> java.lang.String.new("abc") == "abc"
=> true
irb(main):005:0> "abc" == java.lang.String.new("abc")
=> false
```

Bearing in mind that I've barely used JRuby, can you help me come up with an isolated example that exhibits this behavior?

> This is likely due to an ordering issue with the === operator; the Ruby object should instead be responsible for determining equality. 

RSpec isn't aware of which objects are ruby objects and which are java objects.  It simply uses the common `==` and `===` protocols for the matching, and if objects are provided which do not implement those protocols as expected, trouble can result.  Still, I'd like to find a way to fix this for you, and you're right that it's likely due to the fuzzy matching logic in rspec-support.  I'll go pick up the conversation on the issue you opened there.

**Comment by asthasr** [comment]
myronmarston, you may find the other issue (on rspec-support) more enlightening. I filed it after chasing it down a bit further.

The trouble is that most stdlib classes are going to be coerced internally by JRuby; so a class like `java.lang.String` is going to have any Ruby `String` instance coerced to a java string. It's only in custom classes that you'll see this behavior, I think.
