### ISSUE TITLE
Mocking AR methods causes DB errors in 3.3

### ISSUE THREAD

**Issue by somebody32** [rspec/rspec-mocks#975]
Hi, I'm trying to upgrade from 3.2 to 3.3 and getting a lot of db-level errors:

```ruby
Failure/Error: allow(klass).to receive(:find_by_id).with(id).and_return(return_value)
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Incorrect table name '': SHOW FULL FIELDS FROM ``
```

But if I set `mocks.verify_partial_doubles` to `false` then everything become green again. In 3.2 with activated `verify_partial_doubles` everything works too

**Comment by JonRowe** [comment]
Are you using `rspec-rails`?

**Comment by somebody32** [comment]
@JonRowe yes, `3.3.1`

**Comment by JonRowe** [comment]
What is klass in this instance?

**Comment by somebody32** [comment]
subclass of ActiveRecord::Base

**Comment by JonRowe** [comment]
Can you provide more of a snippet? It looks like its either not a working active record model, or something is going wrong with the database connection before we call `define_attribute_methods` on it (which is done in rspec-rails as part of the verification process). Can you also provide the full backtrace of this error (use `--backtrace`)?

**Comment by somebody32** [comment]
@JonRowe updated previous comment, looks like the problem is only with children of `abstract_class` (not sure for 100%, too many errors to go through)

```
Failures:

  1) Rembed::EntityRepository finding conversations
     Failure/Error: allow(klass).to receive(:find_by_id).with(id).and_return(return_value)
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Incorrect table name '': SHOW FULL FIELDS FROM ``
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/mysql2_adapter.rb:213:in `execute'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:259:in `execute_and_free'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:426:in `columns'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:229:in `yield'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:229:in `columns'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/ignorable-0.2.0/lib/ignorable.rb:12:in `columns'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:249:in `column_names'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/attribute_methods.rb:66:in `block in define_attribute_methods'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/attribute_methods.rb:63:in `synchronize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/attribute_methods.rb:63:in `define_attribute_methods'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/validates_timeliness-3.0.14/lib/validates_timeliness/orm/active_record.rb:25:in `define_attribute_methods'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-rails-3.3.1/lib/rspec/rails/active_record.rb:15:in `block (2 levels) in initialize_activerecord_configuration'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:103:in `call'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:103:in `block in initialize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:102:in `each'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:102:in `initialize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:345:in `initialize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:154:in `new'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:154:in `proxy_not_found_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `block (2 levels) in proxy_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `fetch'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:108:in `block in proxy_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `synchronize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/space.rb:106:in `proxy_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:394:in `superclass_proxy'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/proxy.rb:369:in `original_method_handle_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:37:in `original_method'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/method_double.rb:26:in `original_implementation_callable'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:166:in `initialize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:182:in `new'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:182:in `for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:99:in `block in initialize'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:24:in `yield'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:24:in `ensure_implemented'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/verifying_proxy.rb:9:in `add_stub'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/matchers/receive.rb:96:in `setup_method_substitute'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/matchers/receive.rb:84:in `setup_mock_proxy_method_substitute'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/matchers/receive.rb:41:in `setup_allowance'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/targets.rb:45:in `define_matcher'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-mocks-3.3.0/lib/rspec/mocks/targets.rb:14:in `block in delegate_to'
     # ./engines/rembed/spec/services/rembed/entity_repository_spec.rb:47:in `stub_finder'
     # ./engines/rembed/spec/services/rembed/entity_repository_spec.rb:23:in `block (3 levels) in <module:Rembed>'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:378:in `instance_exec'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:378:in `instance_exec'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:357:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:520:in `each'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:607:in `block in run_example_hooks_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:606:in `reverse_each'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:606:in `run_example_hooks_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:476:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:424:in `run_before_example'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:205:in `block in run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:388:in `block in with_around_example_hooks'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:478:in `block in run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:616:in `run_around_example_hooks_for'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/hooks.rb:478:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:388:in `with_around_example_hooks'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example.rb:203:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:559:in `block in run_examples'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:555:in `map'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:555:in `run_examples'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:521:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `block in run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `map'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/example_group.rb:522:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `map'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1627:in `with_suite_hooks'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:114:in `block in run_specs'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/reporter.rb:77:in `report'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:113:in `run_specs'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:89:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:73:in `run'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:41:in `invoke'
     # /home/vagrant/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.3.0/exe/rspec:4:in `<top (required)>'
     # /home/vagrant/.rbenv/versions/2.1.2/bin/rspec:23:in `load'
     # /home/vagrant/.rbenv/versions/2.1.2/bin/rspec:23:in `<main>'
```

**Comment by JonRowe** [comment]
Yep got it, it's an rspec-rails bug, although I'm surprised it worked in 3.2

**Comment by somebody32** [comment]
wow, what a speed, thanks a lot @JonRowe!

**Comment by JonRowe** [comment]
The `master` version of RSpec Rails should now fix this for you
